Feature/163388496 restored implement file download endpoint
gxa/atlas pull request #241
Opened 2019-03-21 10:08 UTC by lingyun1010

2019-03-21 10:45 UTC, alfonsomunozpomer requested changes
Better! Some minor issues remain, please have a look.

2019-03-21 10:45 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +                    @RequestParam(value = "accessKey", defaultValue = "") String accessKey) throws IOException {
`accessKey`should be removed in this endpoint, too. Also, if requesting multiple experiments, for which one would the key be for?

2019-03-21 10:45 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +        String archiveName = accessions.size() + "-" + "experiment" + "-files.zip";
Compact your strings as much as possible:
```java
String archiveName = accessions.size() + "-experiment-files.zip"
```

2019-03-21 10:45 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +        for (String accession : accessions){
Be consistent with your blank spaces. Please do something to integrate CheckStyle into your workflow.

2019-03-21 10:45 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +            if(experiment != null) {
When will `experiment` be `null`?

2019-03-21 10:45 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/ExperimentFileLocationService.java
> +                        Arrays.asList(
Please build lists here again with `ImmutableList.of()`. Now that you’re at it, could you change other occurrences of `Arrays.asList()`?

2019-03-21 14:18 UTC, lingyun1010 commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +            if(experiment != null) {
This is in case any experiment accession in the `RequestParam` is not valid, and the endpoint may still return the files for correct ones.

2019-03-22 12:01 UTC, alfonsomunozpomer requested changes
There are some comments about code conventions that we use in our codebase that we want to keep for consistency. Other tidbits are parts of the Java library API that you’re not familiar with.

The most concerning problem right now are the tests. They’re not actually checking that the downloaded zip archive is well-formed. I’m not sure if it’s possible to test the contents, but we should definitely try to. Please have a look into that.

2019-03-22 12:01 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +                System.out.println("Experiment accession is not valid: " + accession);
We don’t print anything to `System.out`. Who will see it? If you want to log any error message use a logger, which outputs messages to a file that we can inspect at any time. There are many classes that do this if you need examples.

2019-03-22 12:01 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +        List<Experiment> experiments = new ArrayList<Experiment>();
A couple of things: if you’re not going to modify the list remember to always use an `ImmutableList.Builder`.

Also, this kind of loops are better expressed using streams, variable definition and initialisation go together:
```java
ImmutableList<Experiment> experiments = accessions.stream()
    .map(experimentTrader::getPublicExperiment)
    .collect(toImmutableList())
```

2019-03-22 12:01 UTC, alfonsomunozpomer commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +        if (experiments.size() >= 1) {
A more idiomatic way of checking this condition is `!experiments.isEmpty()`.

2019-03-22 12:01 UTC, alfonsomunozpomer commented on sc/src/test/java/uk/ac/ebi/atlas/download/FileDownloadControllerWIT.java
> +    private static final List<String> INVALID_EXPERIMENT_ACCESSION_LIST = Arrays.asList("E-MTAB", "E-EHCA");
Remember to use `ImmutableList`. There is a handy shorthand constructor:
```
ImmutableList.of("E-MTAB", "E-EHCA")
```

2019-03-22 12:01 UTC, alfonsomunozpomer commented on sc/src/test/java/uk/ac/ebi/atlas/download/FileDownloadControllerWIT.java
> +                .param("accession", EXPERIMENT_ACCESSION_LIST.toString().replace("[", "").replace("]", "")))
I can observer two problems here.

The first one is that instead of manipulating a string-serialised list you can do:
```java
String.join(",", EXPERIMENT_ACCESSION_LIST)
```
This is a lot less error prone.

The second is that we decided to change the URL format to be `?accession={accession1}&accession={accession2}` but this is setting the request parameter to `?accession={accession1},{accession2}`, isn’t it? I think that just checking HTTP status codes is insufficient in all these tests. I guess you could get the contents of the response and inspect to see that it contains what you’d expect.

2019-03-22 15:00 UTC, lingyun1010 commented on sc/src/test/java/uk/ac/ebi/atlas/download/FileDownloadControllerWIT.java
> +                .param("accession", EXPERIMENT_ACCESSION_LIST.toString().replace("[", "").replace("]", "")))
Yes. I see what you mean by different URL format, but Spring will parse the `?accession={accession1}&accession={accession2}` into `?accession={accession1},{accession2}`, right, so both request parameter formats are working fine.

2019-03-22 15:38 UTC, lingyun1010 commented on sc/src/main/java/uk/ac/ebi/atlas/download/FileDownloadController.java
> +        List<Experiment> experiments = new ArrayList<Experiment>();
Yeah, but we want to use `try` and `catch` to add only valid experiments in this case, I think the code is simple by using a for loop.

2019-03-22 15:54 UTC, alfonsomunozpomer commented on sc/src/test/java/uk/ac/ebi/atlas/download/FileDownloadControllerWIT.java
> +                .param("accession", EXPERIMENT_ACCESSION_LIST.toString().replace("[", "").replace("]", "")))
I can understand that, but you’re testing a feature that we’re not actually offering. Remember that we want to stick to a standard URL scheme. The test should build the URL by chaining `.param("accession", ...)` multiple times.

2019-03-22 16:40 UTC, lingyun1010 commented
As for the content of archive I have added a test in `ExperimentFileLocationServiceIT`. In `FileDownloadControllerWIT`, the archive is not only tested by `status` but also the `filename` which is corresponding to the number of valid experiment accessions.

2019-03-25 23:30 UTC, alfonsomunozpomer commented on sc/src/test/java/uk/ac/ebi/atlas/download/FileDownloadControllerWIT.java
> +                .andExpect(header().string("Content-Length", String.valueOf(EXPERIMENT_ACCESSION_LIST.size() * 10)))
Why does the Content-Length header need to match that specific value? How does that indicate the validity of the zip file?

2019-04-01 15:55 UTC, alfonsomunozpomer requested changes
This is a lot better. Just needs a bit of extra sugar for completeness.

2019-04-01 15:55 UTC, alfonsomunozpomer commented on sc/src/test/java/uk/ac/ebi/atlas/download/FileDownloadControllerWIT.java
> +                .andExpect(content().string(containsString(zipInputStream.getNextEntry().getName())))
You should test that the zip archive contains **all** the file names you expect, not only one.

2019-04-03 15:09 UTC, alfonsomunozpomer requested changes
Oh no! You are now checking the raw response as a string. The fact that the name of the files is even readable is just a bit of fluke, since it’s a binary file. You should check the `ZipEntry` names against the expected file names.

2019-04-23 12:25 UTC, alfonsomunozpomer commented
Continues in https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/3.

2019-04-23 12:25 UTC, closed without merging